In [73]:
from PIL import Image 
import cv2
image_file = Image.open("/Users/ilyakasimov/Documents/text_recognition/ru_notebooks/images/2878.jpg") # open colour image
image_file = image_file.convert('1') # convert image to black and white
image_file.save('result.jpg')

In [74]:
import cv2
import numpy as np

# Read image
img = cv2.imread('/Users/ilyakasimov/Documents/text_recognition/ru_notebooks/images/2840.jpg')

# threshold 
lower = np.array([0, 0, 0])
upper = np.array([255, 100, 100])
thresh = cv2.inRange(img, lower, upper)
print(thresh)
    
# Change non-red to white
result = img.copy()
result[thresh != 255] = (255,255,255)

# save results
cv2.imwrite('red_numerals_thresh.jpg', thresh)
cv2.imwrite('red_numerals_result.jpg', result)

# cv2.imshow('thresh', thresh)
# cv2.imshow('result', result)
# cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [180]:
img = cv2.imread('/Users/ilyakasimov/Documents/text_recognition/ru_notebooks/images/2745.jpg')

In [185]:
res = np.where(((img[...,0] >= img[...,1] * 1.05) & (img[...,0] >= img[...,2] * 1.05)), 0, 255).astype(np.uint8)

In [186]:
cv2.imwrite('govno.jpg', res)

True